### ISSUE TITLE
Waiting for missing types to be registered: - azureiothub

### ISSUE THREAD

**Issue by sandrisj** [lcarli/NodeRedIoTHub#13]
I am getting following errors, any ideas what could be a problem?

I followed the instructions but now luck.

I tired to reinstalled npm, tried several node.js versions still no luck.

Welcome to Node-RED
===================

22 Nov 13:15:47 - [info] Node-RED version: v0.17.5
22 Nov 13:15:47 - [info] Node.js  version: v8.9.1
22 Nov 13:15:47 - [info] Linux 4.4.0-101-generic x64 LE
22 Nov 13:15:47 - [info] Loading palette nodes
22 Nov 13:15:48 - [warn] ------------------------------------------------------
22 Nov 13:15:48 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
22 Nov 13:15:48 - [warn] [Azure] Error: azureiothub already registered (line:191)
22 Nov 13:15:48 - [warn] ------------------------------------------------------
22 Nov 13:15:48 - [info] Settings file  : /home/parallels/.node-red/settings.js
22 Nov 13:15:48 - [info] User directory : /home/parallels/.node-red
22 Nov 13:15:48 - [info] Flows file     : /home/parallels/.node-red/flows_ubuntu.json
22 Nov 13:15:48 - [info] Server now running at http://127.0.0.1:1880/
22 Nov 13:15:48 - [info] Waiting for missing types to be registered:
22 Nov 13:15:48 - [info]  - azureiothub
22 Nov 13:16:26 - [info] Stopping flows
22 Nov 13:16:26 - [info] Stopped flows
22 Nov 13:16:26 - [info] Waiting for missing types to be registered:
22 Nov 13:16:26 - [info]  - azureiothub
22 Nov 13:17:05 - [info] Stopping flows
22 Nov 13:17:05 - [info] Stopped flows
22 Nov 13:17:05 - [info] Waiting for missing types to be registered:
22 Nov 13:17:05 - [info]  - azureiothub
22 Nov 13:17:23 - [info] Stopping flows
22 Nov 13:17:23 - [info] Stopped flows
22 Nov 13:17:23 - [info] Waiting for missing types to be registered:
22 Nov 13:17:23 - [info]  - azureiothub

**Comment by Kenesuu** [comment]
Have you by any chance previously installed the node from node-red-contrib-azureiothub? If that node is also installed it will create an error together with this contribution. I had this problem and solved it simply by deleting the first node.

**Comment by rasavant-ms** [comment]
Hello @sandrisj,
Were you able to get around this issue yet?
The solution mentioned by @Kenesuu is correct. (Thanks @Kenesuu !)

The reason you are seeing this error is because there is a previously installed node from node-red-contrib-azureiothub.
I would recommend you to delete the node-red-contrib-azureiothub directory from both of these locations on your machine:
1. ~/node-modules --- basically this directory should be in the same location as your .node-red directory
2. ~/AppData/Roaming/npm/node_modules -- this will be the %appdata% location on your machine

Once you delete the directory, try starting node-red again.
