### ISSUE TITLE
missing type

### ISSUE THREAD

**Issue by lucarv** [lcarli/NodeRedIoTHub#4]
I can't get to send messages, it will not deploy the flow.
If i only deploy the device registration flow, it works.
Any hints?

17 Jan 10:35:37 - [info] Node-RED version: v0.16.1
17 Jan 10:35:37 - [info] Node.js  version: v7.2.0
17 Jan 10:35:37 - [info] Windows_NT 10.0.14393 x64 LE
17 Jan 10:35:38 - [info] Loading palette nodes
17 Jan 10:35:41 - [warn] ------------------------------------------------------
17 Jan 10:35:41 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
17 Jan 10:35:41 - [warn] [azureiothubnode] Error: azureiothub already registered
17 Jan 10:35:41 - [warn] ------------------------------------------------------
17 Jan 10:35:41 - [info] Settings file  : \Users\lucarv\.node-red\settings.js
17 Jan 10:35:41 - [info] User directory : \Users\lucarv\.node-red
17 Jan 10:35:41 - [info] Flows file     : \Users\lucarv\.node-red\scratch.json
17 Jan 10:35:41 - [info] Creating new flow file
17 Jan 10:35:41 - [info] Starting flows
17 Jan 10:35:41 - [info] Started flows
17 Jan 10:35:41 - [info] Server now running at http://127.0.0.1:1880/
17 Jan 10:36:38 - [info] Stopping flows
17 Jan 10:36:38 - [info] Stopped flows
17 Jan 10:36:38 - [info] Waiting for missing types to be registered:
17 Jan 10:36:38 - [info]  - azureiothub

**Comment by rasavant-ms** [comment]
Hello @sandrisj,
Were you able to get around this issue?

The reason you are seeing this error is because there is a previously installed node from node-red-contrib-azureiothub.
I would recommend you to delete the node-red-contrib-azureiothub directory from both of these locations on your machine:
~/node-modules --- basically this directory should be in the same location as your .node-red directory
~/AppData/Roaming/npm/node_modules -- this will be the %appdata% location on your machine

Once you delete the directory, try starting node-red again.

Feel free to reopen this issue if this does not work.
